name: PHP Composer

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  COMPOSER_ARGS: "--dev"

jobs:
  build:
    strategy:
      matrix:
        php-version: ['7.2', '7.3', '7.4']
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
    - run: composer self-update
    - run: composer require --dev phpunit/phpunit:^8.5 --no-interaction --no-suggest --no-progress
    - run: composer require --dev phpstan/phpstan:^0.12 --no-interaction --no-suggest --no-progress
    - run: composer require --dev friendsofphp/php-cs-fixer:^2.16 --no-interaction --no-suggest --no-progress
    - run: composer require --dev php-coveralls/php-coveralls:^2.2 --no-interaction --no-suggest --no-progress
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
    - name: Run Composer check
      run: composer check-all
    - name: Code coverage
      run: vendor/bin/php-coveralls --coverage_clover=coverage-report.clover -v
